version: '3.8'
services:
  postgres:
    image: postgres:13
    container_name: openmusic_db
    restart: always
    environment:
      POSTGRES_USER: openmusic
      POSTGRES_PASSWORD: password123
      POSTGRES_DB: openmusicdb
    ports:
      - '5432:5432'